TG/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'', include('app.urls', namespace='app')),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^registrar/$', views.registrar, name='registrar'),
    url(r'^sair/$', views.sair, name='sair'),
]

users/models.py
from django.db import models

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from actions._login import run_login
from actions._usuario_registrar import run_usuario_registrar
from actions._sair import run_sair

from classes.util import *



def login(request):
    #print(request.session.get('sessao_hash', 'nem tem'))
    if request.method == 'POST':
        context = run_login(request)

        print(context)
        if context['resultado']:
            response = HttpResponseRedirect(reverse('app:index'))

            request.session['sessao_hash'] = context['sessao_hash']
            request.session['usuario_id'] = context['usuario_id']
            return response
        else:
            return render(request, 'users/login.html', context)
    else:
        return render(request, 'users/login.html', {})


def registrar(request):
    if request.method == 'POST':
        context = run_usuario_registrar(request)

        if context['resultado']:
            return HttpResponseRedirect(reverse('users:login'))#render(request, 'users/login.html', {})
        else:
            return render(request, 'users/usuario_registrar.html', {})
    else:
        return render(request, 'users/usuario_registrar.html', {})


def sair(request):
    context = run_sair(request)

    return HttpResponseRedirect(reverse('users:login'))

app/templates/users/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Normalizador | Login</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% block css %}
        {% endblock css %}


        <script type="text/javascript" src="{% static 'jquery/jquery-3.1.1.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static '3rd/simple-sidebar.css' %}">

        <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
        <script type="text/javascript" src="{% static 'scripts/util.js' %}"></script>
        <script type="text/javascript" src="{% static 'scripts/3rd_scripts/js-cookie.js' %}"></script>
    </head>

    <body>
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-3" style="margin-top:150px">
                        <div>
                            {% block content %}
                            {% endblock content %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script>
            $("#menu-toggle").click(function(e){
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });
        </script>

    </body>
</html>

{% block script %}
{% endblock script %}

app/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}
    {% if form.errors %}
        <p>Usuário e senha não correspondem</p>
    {% endif %}

    {% if erro %}
        <div id="div-erro" class="erro" style="text-align:center;">
            {{erro}}
        </div>
    {% endif %}

    <div style="text-align:center">
        <h3>Entrar</h3>
        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="email@email.com"/>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="senha" id="senha" placeholder="****"/>
            </div>

            <button class="btn btn-enviar col-md-12" name="submit">ENTRAR</button>
        </form>

        <div style="margin-left: 70%">
            <a href="{% url 'users:registrar' %}">registrar</a>
        </div>
    </div>

{% endblock content %}


{% block script %}
    <script>
        {% if erro %}
            $(document).ready(function(){
                setTimeout(
                    function(){ $("#div-erro").fadeOut(); }, 2000
                );
            });
        {% endif %}
    </script>
{% endblock script %}

app/templates/users/usuario_registrar.html
{% extends "users/base.html" %}
{% load bootstrap %}
{% load static %}

{% block content %}

    <div style="text-align:center">
        <h3>Registrar</h3>
        <form action="{% url 'users:registrar' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="nome" id="nome" placeholder="nome"/>
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="email@email.com"/>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="senha" id="senha" placeholder="****"/>
            </div>

            <button class="btn btn-enviar col-md-12" name="submit">REGISTRAR</button>
        </form>

        <div style="margin-left: 70%">
            <a href="{% url 'users:login' %}">entrar</a>
        </div>
    </div>

{% endblock content %}