TG/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'', include('app.urls', namespace='app')),
]

app/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),

    #url tabelas
    url(r'^tabelas/$', views.tabelas, name='tabelas'),
    url(r'^tabelas/(?P<table_id>\d+)/$', views.tabela, name='tabela'),
    url(r'^add_tabela/$', views.add_tabela, name='add_tabela'),

    #url campos
    url(r'^add_campo/(?P<table_id>\d+)/$', views.add_campo, name='add_campo'),

    #url documentos
    url(r'^documentos/$', views.documentos, name='documentos'),
    url(r'^documentos/(?P<documento_id>\d+)/$', views.documento, name='documento'),
    url(r'^documentos/adicionar/$', views.add_documento, name='add_documento'),
    url(r'^documentos/(?P<documento_id>\d+)/deletar/$', views.documento_deletar, name='documento_deletar'),
    url(r'^documentos/(?P<documento_id>\d+)/script/$', views.script_documento, name='script_documento'),
    url(r'^documentos/(?P<documento_id>\d+)/diagrama/$', views.diagrama_documento, name='diagrama_documento'),
    url(r'^documentos/(?P<documento_id>\d+)/dados/$', views.inserir_dados_exemplo, name='inserir_dados_exemplo'),

    #url normalizar
    #url(r'^normalizar/$', views.normalizar, name='normalizar'),
    #url(r'^normalizar/(?P<table_id>\d+)/$', views.normalizar, name='normalizar'),

    #url normalizar documento
    url(r'^normalizar/(?P<documento_id>\d+)/$', views.normalizar_documento, name='normalizar'),

    #ajax
    url(r'^ajax_add_tabela/$', views.ajax_add_tabela, name='ajax_add_tabela'),
    url(r'^ajax_add_campo/$', views.ajax_add_campo, name='ajax_add_campo'),
    url(r'^ajax_renomear_tabela/$', views.ajax_renomear_tabela, name='ajax_renomear_tabela'),
    url(r'^ajax_tabela/(?P<tabela_id>\d+)/$', views.ajax_tabela, name='ajax_tabela'),
    url(r'^ajax_get_tabelas/(?P<tabela_id>\d+)/$', views.ajax_get_tabelas, name='ajax_get_tabelas'),
    url(r'^ajax_get_chaves/(?P<tabela_id>\d+)/$', views.ajax_get_chaves, name='ajax_get_campos'),
    url(r'^ajax_compartilhar_documento/$', views.ajax_compartilhar_documento, name='ajax_compartilhar_documento'),
    url(r'^ajax_desnormalizar_documento/$', views.ajax_desnormalizar_documento, name='ajax_desnormalizar_documento'),
    url(r'^ajax_dados_exemplo/$', views.ajax_dados_exemplo, name='ajax_dado_exemplo'),

    #grupo
    url(r'^grupos/$', views.grupos, name='grupos'),
    url(r'^grupos/(?P<grupo_id>\d+)/$', views.grupo, name='grupo'),
    url(r'^grupos/registrar/$', views.grupo_registrar, name='grupo_registrar'),
    url(r'^grupos/(?P<grupo_id>\d+)/usuario/$', views.grupo_adicionar_usuario, name='grupo_adicionar_usuario'),
    url(r'^grupos/convite/$', views.grupo_convite, name='grupo_convite'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^registrar/$', views.registrar, name='registrar'),
    url(r'^sair/$', views.sair, name='sair'),
]

app/templates/app/add_documento.html
{% extends 'app/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Novo Documento</title>

    <style>
        #add_campo:hover{ color:white; background-color:rgba(61, 61, 103,.9); }
    </style>
{% endblock css %}

{% block header %}
    <h3>Novo Documento</h3>

    <span class="erro" id="msg-erro" style="font-weight:bold; display:none; margin-top:10px;color:rgba(0,0,0,.7)">as</span>
{% endblock header %}

{% block content %}
    <form action="{% url 'app:add_documento' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form_documento %}

        <div class="input" style="margin-bottom: 10px">
            <label for="grupo">Grupo</label>
            <select class="form-control" id="grupo" name="grupo" required>
                {% for grupo in grupos %}
                    <option value="{{grupo.id}}">{{grupo}}</option>
                {% endfor %}
            </select>
        </div>

        <div style="margin: 30px 0 50px 0">
            <h4>Campos
                <button type="button" id="add_campo" class="btn btn-default" data-toggle="modal" data-target="#addCampo">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
            </h4>

            <div id="campos" class="col-md-12"></div>
        </div>

        {% buttons %}
            <button name="submit" class="btn btn-enviar">SALVAR</button>
        {% endbuttons %}
    </form>
{% endblock content %}

{% block modal %}
    <div id="addCampo" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times</button>
                    <h4 class="modal-title">Adicionar Campo</h4>
                </div>
                <div class="modal-body">
                    <div class="input" style="margin-bottom: 10px">
                        <label for="temp_nome">Campo</label>
                        <input class="form-control" id="temp_nome" maxlength="20" placeholder="Campo" required="required" type="text" />
                    </div>

                    {% buttons %}
                        <button name="submit" class="btn btn-enviar" id="btnAddCampo" data-dismiss="modal">ADICIONAR</button>
                    {% endbuttons %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" id="fechar_modal" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock modal %}


{% block script %}
    <script>
        var num = 0;
        var campos = new Array();

        $("#btnAddCampo").click(function(){
            let nome = $("#temp_nome").val();

            nome = normalizarNome(nome);

            if(nome == '')
                alert("Insira um nome válido para o campo!");
            else if(campos.indexOf(nome)!=-1){
                $("#msg-erro").fadeIn();
                $("#msg-erro").text("Já existe um campo com esse nome!");
                setTimeout(function(){$("#msg-erro").fadeOut();}, 2000);

                $("#temp_nome").val("");
            }
            else{
                let dom = '<div class="form-group col-md-12" id="item_'+num+'">';
				dom += '<span class="glyphicon glyphicon-remove remove" aria-hidden="true" id="remove_'+num+'" onclick="removeCampo('+num+');"></span>';
                dom += '<input type="text" class="form-control nome-campo" id="campo_'+num+'" name="campo['+num+']" value="'+nome+'" ';
                dom += ' onfocusout="atualizaNormal('+num+');alterarOut(this);" onfocusin="alterarIn(this);" style="display:inline-block; width:40%" />';
                dom += '</div>';
                $("#campos").append(dom);

                $("#temp_nome").val("");

                campos.push(nome);
            }

            num++;
        });


        function alterarIn(dom){
            let temp = $(dom).val();
            let index = campos.indexOf(temp);

            if(index!=-1)
                campos.splice(index, 1);
        }

        function alterarOut(dom){
            let temp = $(dom).val();

            if(campos.indexOf(temp)!=-1){
                $("#msg-erro").fadeIn();
                $("#msg-erro").text("Já existe um campo com esse nome!");
                setTimeout(function(){$("#msg-erro").fadeOut();}, 2000);

                $(dom).val("");
                $(dom).focus();
            }else if(temp)
                campos.push(temp);
        }


        $("#id_name").focusout(function(){
            var nome = '';
            nome = $(this).val();
            nome = normalizarNome(nome);
            $(this).val(nome);
        });

        function atualizaNormal(num){
            var nome = $("#campo_"+num).val();
            nome = normalizarNome(nome);

            if(nome == '')
                $("#campo_"+num).focus();
            else
                $("#campo_"+num).val(nome);
        }

        function removeCampo(num){
            $("#item_"+num).remove();
        }


        $("#temp_nome").keyup(function(e){
            let codigo = e.which;

            if(codigo==13)
                $("#btnAddCampo").click();
        });

    </script>
{% endblock script %}

app/templates/app/add_tabela.html
{% extends 'app/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h3>Nova Tabela</h3>
{% endblock header %}

{% block content %}
    <form action="{% url 'app:add_tabela' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">SALVAR</button>
        {% endbuttons %}
    </form>
{% endblock content %}

app/templates/app/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% block css %}
        {% endblock css %}


        <script type="text/javascript" src="{% static 'jquery/jquery-3.1.1.js' %}"></script>
        <!--<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>-->

        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static '3rd/simple-sidebar.css' %}">
		<!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">-->

        <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
        <script type="text/javascript" src="{% static 'scripts/util.js' %}"></script>
        <!--<script type="text/javascript" src="{% static 'scripts/3rd_scripts/js-cookie.js' %}"></script>-->
    </head>

    <body>
        <div id="wrapper" class="toggled">
            {% block sidebar %}
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="{% url 'app:index' %}">
                            {{usuario}}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'users:sair' %}">sair</a>
                    </li>
                    <li class="divisor"></li>
                    <li>
                        <a href="{% url 'app:grupos' %}">Grupos</a>
                    </li>
                    <li>
                        <a href="{% url 'app:documentos' %}">Documentos</a>
                    </li>
                    <li>
                        <a href="{% url 'app:tabelas' %}">Tabelas</a>
                    </li>
                </ul>
            </div>
            {% endblock sidebar %}

            <a href="#menu-toggle" class="btn btn-toggle" id="menu-toggle"><</a>

            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="page-header">
                                {% block header %}
                                {% endblock header %}
                            </div>

                            <div>
                                {% block content %}
                                {% endblock content %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% block modal %}
        {% endblock modal %}

        <script>
            $("#menu-toggle").click(function(e){
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");

                if($("#wrapper").attr("class") == "toggled")
                    $("#menu-toggle").text("<");
                else
                    $("#menu-toggle").text(">");
            });
        </script>

    </body>
</html>

{% block script %}
{% endblock script %}

app/templates/app/documento.html
{% extends  'app/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block css %}
    <title>Documento | {{documento}}</title>
{% endblock css %}

{% block header %}
    <h3>
        <span class="col-md-10">{{documento}}</span>
        <small>
            <span class="glyphicon glyphicon-copy" id="desnormalizar-documento" title="Desnormalizar"></span>
            <span class="glyphicon glyphicon-share" id="compartilhar-documento" data-toggle="modal" data-target="#modal-compartilhar" title="Compartilhar"></span>
        </small>
    </h3>

    {% if fn == 0 %}
        Documento desnormalizado<br>
        {% if flag_dados %}
            <a href="{% url 'app:normalizar' documento.id %}">normalizar</a>
            <br>
        {% endif %}

        <a href="{% url 'app:inserir_dados_exemplo' documento.id %}">inserir dados</a>
    {% elif fn < 3 %}
        Forma Normal atual: {{fn}}<br>
        <a href="{% url 'app:normalizar' documento.id %}">normalizar</a><br>
    {% elif fn == 3 %}
        Documento Normalizado<br>
        <a href="{% url 'app:script_documento' documento.id %}">gerar script</a><br>
        <a href="{% url 'app:diagrama_documento' documento.id %}">gerar diagrama</a>
    {% endif %}

    <div id="mensagem" class="div-msg" style="display:none;">
        <span class="span-msg"></span>
    </div>

{% endblock header %}

{% block content %}
    {% if fn == 0 %}
        <div class="lista">
            {% if sem_tabela %}
                <div class="header" onclick="mostrar_campos(666);">Campos sem tabela</div>
                <div style="display:none" id="campos_666">
                    {% for campo in sem_tabela %}
                        <div class="item-lista">{{campo}}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    {% endif %}

    <div class="espacamento"></div>

    {% if tabelas %}<h4>Tabelas do documento {{documento}}</h4>{% else %}<h4>Não há tabelas registradas para o documento {{documento}}</h4>{% endif %}

    <div class="lista">
        {% for tabela in tabelas %}
            <div class="header" onclick="mostrar_campos({{tabela.id}});">
                {{tabela}}
            </div>

            <div style="display:none" id="campos_{{tabela.id}}">
                {% for chave in tabela.chaves %}
                    <div class="item-lista">
                        <div style="width:20px; display:inline-block">
                            <img src="{% static 'imagens/gold_key.png' %}" width="17"/>
                        </div>
                        {{chave}}
                    </div>
                {% endfor %}
                {% for chave in tabela.estrangeiras %}
                    <div class="item-lista">
                        <div style="width:20px; display:inline-block">
                            <img src="{% static 'imagens/green_key.png' %}" width="17"/>
                        </div>
                        {{chave}}
                    </div>
                {% endfor %}
                {% for campo in tabela.campos %}
                    <div class="item-lista" style="padding-left:55px">{{campo}}</div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}


{% block modal %}
    <div id="modal-compartilhar" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Compartilhar Documento</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label" for="grupo-receber">Grupo</label>
                        <select class="form-control" id="grupo-receber">
                            {% for grupo in grupos %}
                                <option value="{{grupo.id}}">{{grupo}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="modo-compartilhar">Forma</label>
                        <select class="form-control" id="modo-compartilhar">
                            <option value="1">Desnormalizado</option>
                            <option value="2">Atual</option>
                        </select>
                    </div>


                    {% csrf_token %}
                    {% buttons %}
                        <button name="submit" class="btn btn-enviar" id="enviar-compartilhar" data-dismiss="modal">Compartilhar</button>
                    {% endbuttons %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default">Fechar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock modal %}


{% block script %}
    <script>
        function mostrar_campos(tabela_id){
            if($("#campos_"+tabela_id).css("display") == "none")
                $("#campos_"+tabela_id).show();
            else
                $("#campos_"+tabela_id).hide();
        }


        $("#enviar-compartilhar").click(function(){
            let documento_id = {{documento.id}};
            let grupo_id = $("#grupo-receber").val();
            let token = $("input[name=csrfmiddlewaretoken]").val();
            let modo_compartilhar = $("#modo-compartilhar").val();

            if(grupo_id){
                $.ajax({
                    type: "POST",
                    url: '{% url 'app:ajax_compartilhar_documento' %}',
                    data: {
                        'documento_id': documento_id,
                        'grupo_id': grupo_id,
                        'modo_compartilhar': modo_compartilhar,
                        'csrfmiddlewaretoken': token
                    },
                    success: function(ret){
                        let json_ret = JSON.parse(ret.content);

                        if(json_ret.resultado){
                            $("#mensagem").attr("class", "div-msg sucesso");
                            $("#mensagem").text("Documento compartilhado com sucesso!");
                        }
                        else{
                            $("#mensagem").attr("class", "div-msg erro");
                            $("#mensagem").text("Erro ao tentar compartilhar o documento!");
                        }

                        $("#mensagem").show();
                        setTimeout(function(){ $("#mensagem").fadeOut('slow'); }, 2000);
                    }
                });
            }
            else
                alert("Selecione um grupo");
        });


        $("#desnormalizar-documento").click(function(){
            let documento_id = {{documento.id}};
            let token = $("input[name=csrfmiddlewaretoken]").val();

            if(confirm("Deseja desnormalizar o documento?")){
                $.ajax({
                    type: "POST",
                    url: '{% url 'app:ajax_desnormalizar_documento' %}',
                    data: {
                        'documento_id': documento_id,
                        'csrfmiddlewaretoken': token
                    },
                    success: function(ret){
                        console.log(ret);
                        let json_ret = JSON.parse(ret.content);

                        if(json_ret.resultado)
                            location.reload();
                    }
                });
            }
        });

    </script>
{% endblock script %}

app/templates/app/documentos.html
{% extends  'app/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block css %}
    <title>Documentos</title>
{% endblock css %}

{% block header %}
    <h3>Documentos</h3>
    <a href="{% url 'app:add_documento' %}">novo documento</a>

    <div id="mensagem-geral">
        <span></span>
    </div>
{% endblock header %}

{% block content %}
    <div class="lista">
        {% for documento in documentos %}
            <div class="col-md-1 opcoes">
                <span class="glyphicon glyphicon-remove" aria-hidden="true" onclick="if(confirm('Deseja excluir este documento?'))deletar_documento({{documento.id}});"></span>
            </div>
            <div class="header redirecionar" onclick="abrir_documento({{documento.id}});">
                {{documento}}
            </div>
        {% empty %}
            <div>
                Não há documentos cadastrados
            </div>
        {% endfor %}
    </div>

{% endblock content %}


{% block script %}
    <script>
        function deletar_documento(documento_id){
            $.ajax({
                type: "GET",
                url: "/documentos/"+documento_id+"/deletar",
                success: function(ret){
                    let json_ret = JSON.parse(ret.content)
                    if(json_ret.resultado == true)
                        location.reload();
                    else
                    {
                        $("#mensagem-geral").fadeIn();
                        $("#mensagem-geral").addClass("erro");
                        $("#mensagem-geral span").text("Houve um erro ao tentar excluir o documento");

                        setTimeout(
                            function(){
                                $("#mensagem-geral").fadeOut();
                            }, 2000
                        );
                    }
                }
            });
        }

        function abrir_documento(documento_id){
            location.href = "/documentos/"+documento_id;
        }
    </script>
{% endblock script %}

app/templates/app/forma_normal_3.html
{% extends  'app/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block css %}
    <title>Normalizar {{documento}}</title>
    <link  rel="stylesheet" href="{% static 'normalizar.css' %}">
{% endblock css %}

{% block header %}
    <h3 style="display: inline;">Documento {{documento}}</h3>

    <div class="aviso">
        <span class="titulo">3ª Forma Normal</span>
        <span id="texto-dica">
            "Identificar e definir dependencias transitivas entre itens não chaves"
        </span>
    </div>
    <!--<img src="{% static 'imagens/green_key.png' %}" alt="Chave Estrangeira" title="Chave Estrangeira" />-->
{% endblock header %}


{% block content %}
    <form action="{% url 'app:normalizar' documento.id %}" method="POST">
	
        {% for tabela in documento.tabelas %}
            <div style="padding: 15px">
                <h4>{{tabela}}</h4>
                {% for campo in tabela.campos %}
                    <div class="dropdown" style="display: inline">
                        <div class="campo {% if campo.primary %}chave-primaria{% endif %}" id="{{campo}}_campo"
                         onmouseover="mostrarOp('{{campo}}')"
                         onmouseout="esconderOp('{{campo}}')" style="cursor: context-menu">
                            {{campo}}

                            <span class="caret opcoes" style="display: none" id="{{campo}}_op" id="dropdownMenu_{{campo}}" data-toggle="dropdown" 
									aria-haspopup="true" aria-expanded="true"></span>

                            <ul class="dropdown-menu dropdown-menu-meu" aria-labelledby="dropdownMenu_{{campo}}">
                                {% for dep in tabela.campos %}
                                    {% if dep != campo %}
                                        <li onclick="setarDependencia('{{campo}}', '{{dep}}');" class="item_chave_{{campo}}" id="{{campo}}_{{dep}}">
											{{dep}}
										</li>
                                    {% endif %}
                                {% endfor %}
                                <li role="separator" class="divider"></li>
                                <li onclick="limparDependencia('{{campo}}');">Limpar Dependências</li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

        <div style="height: 50px"></div>

        <input type="hidden" name="forma_normal" value="3" />
        {% csrf_token %}
        {% buttons %}
            <button name="submit" class="btn btn-enviar" id="enviar" style="margin-left:15px">SALVAR</button>
        {% endbuttons %}
    </form>
{% endblock content %}

{% block script %}
    <script src="{% static 'scripts/normalizar.js' %}"></script>
    <script>

    </script>
{% endblock script %}

app/templates/app/grupo_adicionar_usuario.html
{% extends "app/base.html" %}
{% load bootstrap %}
{% load static %}

{% block css %}
    <title>Adicionar usuário | {{grupo}}</title>
{% endblock css %}

{% block header %}
    <h3>Enviar solicitação</h3>
{% endblock header %}

{% block content %}
    {% if erro %}
        <div class="erro">
            <span>{{erro}}</span>
        </div>
    {% endif %}

    <form action="{% url 'app:grupo_adicionar_usuario' grupo.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="usuario@email"/>
            </div>
        </div>

        <button class="btn btn-enviar">ENVIAR SOLICITAÇÃO</button>
    </form>
{% endblock content %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block header %}
    <title>Dashboard | {{usuario}}</title>
{% endblock header %}

{% block content %}
    {% if solicitacoes %}
        <h4>Solicitações</h4>
        <div class="lista">
            {% for solicitacao in solicitacoes %}
                <div class="opcoes col-md-1">
                    <span class="glyphicon glyphicon-ok" alt="Aceitar" title="Aceitar" onclick="aceitar({{solicitacao.grupo.id}});" style="margin-right:10px"></span>
                    <span class="glyphicon glyphicon-remove" alt="Excluir" title="Excluir" onclick="if(confirm('Deseja rejeitar a solicitação do grupo?')) rejeitar({{solicitacao.grupo.id}});"></span>
                </div>
                <div class="header">
                    {{solicitacao.grupo}}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% csrf_token %}

{% endblock %}

{% block script %}
    <script>
        function aceitar(id_grupo){
            var token = $("input[name=csrfmiddlewaretoken]").val();

            $.ajax({
                type: "POST",
                url: '{% url 'app:grupo_convite' %}',
                data: {
                    'csrfmiddlewaretoken': token,
                    'aceitar': '1',
                    'grupo': id_grupo
                },
                success: function(ret){
                    location.reload();
                }
            });
        }

        function rejeitar(id_grupo){
            var token = $("input[name=csrfmiddlewaretoken]").val();

            $.ajax({
                type: "POST",
                url: '{% url 'app:grupo_convite' %}',
                data: {
                    'csrfmiddlewaretoken': token,
                    'rejeitar': '1',
                    'grupo': id_grupo
                },
                success: function(ret){
                    location.reload();
                }
            });
        }
    </script>
{% endblock script %}

app/templates/app/renomear_tabelas.html
{% extends  'app/base.html' %}
{% load bootstrap3 %}
{% load static %}


{% block css %}
    <title>Normalizar {{documento}}</title>
    <link  rel="stylesheet" href="{% static 'normalizar.css' %}">
{% endblock css %}


{% block header %}
    <h3 style="display: inline;">Documento {{documento}}</h3>

    <h3 style="display: inline;">
    </h3>

    <div class="aviso">
        <span class="titulo"></span>
        <span id="texto-dica">Renomeie as tabelas geradas pela aplicação!</span>
        <span id="mensagem-geral"></span>
    </div>
{% endblock header %}


{% block content %}
    <form action="{% url 'app:documento' documento.id %}" method="POST">
        <ul class="lista">
            {% for tabela in documento.tabelas %}
                <li style="margin-bottom: 20px">
                    <div class="form-group col-md-6">
                      <input type="text" class="form-control nome col-md-6" id="nome_{{tabela.id}}" value="{{tabela}}">
                    </div>
                    {% buttons %}
                        <div class="btn btn-enviar enviar" tabela="{{tabela.id}}">RENOMEAR</div>
                    {% endbuttons %}

                    <div class="lista">
                        {% for campo in tabela.primarias %}
                            <div class="item-lista">
                                <div style="width:20px; display:inline-block">
                                    <img src="{% static 'imagens/gold_key.png' %}" width="17"/>
                                </div>
                                {{campo}}
                            </div>
                        {% endfor %}
                        {% for campo in tabela.estrangeiras %}
                            <div class="item-lista">
                                <div style="width:20px; display:inline-block">
                                    <img src="{% static 'imagens/green_key.png' %}" width="17"/>
                                </div>
                                {{campo}}
                            </div>
                        {% endfor %}
                        {% for campo in tabela.campos %}
                            <div class="item-lista" style="padding-left:50px">
                                {{campo}} {{campo.tipo}}
                            </div>
                        {% endfor %}
                    </div>
                </li>
            {% endfor %}
        </ul>

        {% csrf_token %}
    </form>
{% endblock content %}


{% block script %}
    <script>
        $(".nome").focusout(function(){
            var aux = normalizarNome($(this).val());
            $(this).val(aux);
        });

        $(".enviar").click(function(){
            var codigo_tabela = $(this).attr("tabela");
            var nome = $("#nome_"+codigo_tabela).val();
            nome = normalizarNome(nome);
            var token = $("input[name=csrfmiddlewaretoken]").val();

            $.ajax({
                type: "POST",
                url: '{% url 'app:ajax_renomear_tabela' %}',
                data: {
                    'nome': nome,
                    'tabela': codigo_tabela,
                    'csrfmiddlewaretoken': token
                },
                success: function(){
                    location.reload();
                }
            });
        });
    </script>
{% endblock script %}